apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-selfsigned-crt
  namespace: deeptalk
data:
  nginx-selfsigned.crt: |
    -----BEGIN CERTIFICATE-----
    MIIGZDCCBEygAwIBAgIQDIkfdqF/a91XCXgOwlLuvTANBgkqhkiG9w0BAQwFADBL
    MQswCQYDVQQGEwJBVDEQMA4GA1UEChMHWmVyb1NTTDEqMCgGA1UEAxMhWmVyb1NT
    TCBSU0EgRG9tYWluIFNlY3VyZSBTaXRlIENBMB4XDTI1MDgxNDAwMDAwMFoXDTI1
    MTExMjIzNTk1OVowFzEVMBMGA1UEAxMMZGVtby5ob2hhLmFpMIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkobt3HIfo9Ik2tyRBmci7eDr+IBavucmi8zK
    bDhqWL3PmRKBD9ElK7/F348zX4P4qGvymXcGYZqy/IhGVehTNN1nQG2JMqFxn5aH
    TWrx/YWq5utOTOnEqA50Pn/DxO+SKS64lnLqmcgcHV1nBS644XVzgIDzDROtJORb
    nppkbQlmZBUU89aBSGs3DcOqO1ShNIhpFJgzBYKbVMMo5p2KqaGMmzUncGiHIz+P
    sAhfy0F+2oOy6bCEFOn+EXfQR+tIYFl3p+4CJIarOBe3Ii33R0t/kPkJEL8agbMp
    9Bl+JvXgPL4Mzzzzsh0LSgmH59NaCu6um+LdkYZG8ENcuuTfgwIDAQABo4ICdjCC
    AnIwHwYDVR0jBBgwFoAUyNl4aKLZGWjVPXLeXwo+3LWGhqYwHQYDVR0OBBYEFHSj
    78fYK6xOl83sY0ueSktOB1xmMA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAA
    MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBJBgNVHSAEQjBAMDQGCysG
    AQQBsjEBAgJOMCUwIwYIKwYBBQUHAgEWF2h0dHBzOi8vc2VjdGlnby5jb20vQ1BT
    MAgGBmeBDAECATCBiAYIKwYBBQUHAQEEfDB6MEsGCCsGAQUFBzAChj9odHRwOi8v
    emVyb3NzbC5jcnQuc2VjdGlnby5jb20vWmVyb1NTTFJTQURvbWFpblNlY3VyZVNp
    dGVDQS5jcnQwKwYIKwYBBQUHMAGGH2h0dHA6Ly96ZXJvc3NsLm9jc3Auc2VjdGln
    by5jb20wggECBgorBgEEAdZ5AgQCBIHzBIHwAO4AdQDd3Mo0ldfhFgXnlTL6x5/4
    PRxQ39sAOhQSdgosrLvIKgAAAZimilnrAAAEAwBGMEQCIEMiSlZOSxDtKDryzzEv
    vWmFbb0rbA04ptGt6qUUwN6JAiBdTtRwgUcZRNarRKkxcDjg4bKLRMya0oO2OcdU
    YE6CagB1AA3h8jAr0w3BQGISCepVLvxHdHyx1+kw7w5CHrR+Tqo0AAABmKaKWYYA
    AAQDAEYwRAIgA55Rv236cviP3FFYYFgct32AXHHGdmhps1XqupiM2iICIBNZyIsX
    y4xZy97q1cAiHTQX9FZ7hHA+ruyPaUTeUphAMBcGA1UdEQQQMA6CDGRlbW8uaG9o
    YS5haTANBgkqhkiG9w0BAQwFAAOCAgEAAymxevhCk0JeFpPaBWbNk1igOLrfda+R
    gzv2w1TyhGuRnLSAE+Ep+fPHTi/mBoDv9eFtYWYQwi1dj+45VMhJUzJECHhEasLb
    77LZeXIBnVZkHVSKtCRTcEtq0XSHlNQHj9Zvs6VdOFNQEVBf3A0iQXeVfezUohMX
    BfDLFWcVW2ZRlMNPmig2Ni1sdmEPrm34Qvomd3iZtEB9rphPYba5XwDlwrCCTOQA
    Azssg13SkES9w+mXDlYElugF4/PZI+0ViyhS/M5UJEWfrLF62haVF90Lobgyd7t6
    eNKxYUiAu1GN48uDX5x1tE6vJZFP3s2/2nw9UPOilYQH/hAWf+DRnBCkTBGCEiGY
    xGb4uxQqDFTROKk18fBJ6mYm7nJjhzoIanvlsvI53LJJUjCI+o1Gre1c1+ygkC+k
    trwrQYWc7ba3JeEY8Dsj+dN3OaefhSHjmjvHUIxlv/IM+EmLkYNkBuY3ALnDBkNH
    3sSVDEKf4Mt6YIRkK/keuMnP8+r/6Grwf/9FcgmPmlZumrh4nZBYw+gwdp95y4iE
    qXO0UJ0gnKZzzyN45d7unEuf+oMeyyShh5MVMgAP1134Y7i6rBd8o8/TxSW5wIb6
    iHuEkK/XhmIg6g5OJhQp2f8DTLIauF2A3FZcxTXa86DLHE7CcYAGEE03Um47ldjH
    a1Hb3mKe4TQ=
    -----END CERTIFICATE-----
