# bash test-qwen.sh "凌晨"
# bash test-qwen.sh "早上"
bash test-qwen.sh "上午"
# bash test-qwen.sh "中午"
# bash test-qwen.sh "下午"
# bash test-qwen.sh "傍晚"
# bash test-qwen.sh "晚上"
# bash test-qwen.sh "这两天"
bash test-qwen.sh "这几天"
# bash test-qwen.sh "刚才"
# bash test-qwen.sh "前天"
# bash test-qwen.sh "昨天"
# bash test-qwen.sh "今天"
# bash test-qwen.sh "明天"
# bash test-qwen.sh "后天"
# bash test-qwen.sh "大后天"
# bash test-qwen.sh "上周"
# bash test-qwen.sh "上个月"
# bash test-qwen.sh "上月"
# bash test-qwen.sh "前几天"
# bash test-qwen.sh "本周"
# bash test-qwen.sh "这周"
