apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  runtimeClassName: nvidia
  containers:
  - name: cuda-test
    image: registry.jxit.net.cn:5000/deeptalk/cuda:12.3.2-base-ubuntu22.04
    command: ["sleep", "88888888888888888888"]
    resources:
      limits:
        nvidia.com/gpu: 1
  restartPolicy: OnFailure
