apiVersion: v1
kind: Service
metadata:
  name: deeptalk-etcd
  namespace: deeptalk
spec:
  ports:
    - port: 2379
      name: "etcd-port"
      protocol: TCP
  selector:
    app: deeptalk-etcd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deeptalk-etcd
  namespace: deeptalk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deeptalk-etcd
  template:
    metadata:
      labels:
        app: deeptalk-etcd
    spec:
      containers:
        - name: deeptalk-etcd
          image: registry.jxit.net.cn:5000/deeptalk/etcd:v3.5.18
          env:
            - name: ETCD_AUTO_COMPACTION_MODE
              value: "revision"
            - name: ETCD_AUTO_COMPACTION_RETENTION
              value: "1000"
            - name: ETCD_QUOTA_BACKEND_BYTES
              value: "4294967296"
            - name: ETCD_SNAPSHOT_COUNT
              value: "50000"
          volumeMounts:
            - name: etcd-storage
              mountPath: /etcd
          command: ["etcd", "-advertise-client-urls=http://127.0.0.1:2379", "-listen-client-urls=http://0.0.0.0:2379", "--data-dir=/etcd"]
          livenessProbe:
            httpGet:
              path: /health
              port: 2379
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 20
            failureThreshold: 3
      volumes:
        - name: etcd-storage
          persistentVolumeClaim:
            claimName: deeptalk-etcd-pvc
