apiVersion: apps/v1
kind: Deployment
metadata:
  name: deeptalk-embedding
  namespace: deeptalk
  labels:
    app: deeptalk-embedding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deeptalk-embedding
  template:
    metadata:
      labels:
        app: deeptalk-embedding
    spec:
      runtimeClassName: nvidia
      containers:
        - name: deeptalk-embedding
          image: registry.jxit.net.cn:5000/deeptalk/deeptalk-embedding:git-4
          imagePullPolicy: IfNotPresent
          command: ["python3", "/app/embedding.py"]
          ports:
            - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: deeptalk-embedding
  namespace: deeptalk
spec:
  selector:
    app: deeptalk-embedding
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 8088
  type: NodePort
