apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: deeptalk
data:
  nginx.conf: |
    user  root;
    worker_processes  auto;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       mime.types;
        default_type  application/octet-stream;

        error_log /dev/stderr;
        access_log /dev/stdout;

        sendfile        on;
        keepalive_timeout  65;

        server {
            server_name _;
            listen 18123 ssl https_allow_http;
            # listen 18123 ssl;
            
            # SSL 证书配置（需要替换为您的实际证书路径）
            ssl_certificate certs/nginx-selfsigned.crt;
            ssl_certificate_key certs/nginx-selfsigned.key;
            
            # 修复1：启用TLS 1.2/1.3，禁用不安全的协议
            ssl_protocols TLSv1.2 TLSv1.3;
            ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';
            ssl_prefer_server_ciphers on;

            location /install {
                autoindex on;
                root /usr/local/nginx;
            }
            location /buildin {
                autoindex on;
                root /usr/local/nginx;
            }
            location /v1 {
                if ($http_authorization != "Bearer sk-08018a17f8dd3c83ed5b3087eecf1360") {
                    return 403;  # 如果不匹配，返回403禁止访问
                }
                proxy_pass http://10.42.0.1:8088/v1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            location /api/chat/ws {
                proxy_pass http://deeptalk-xboom.deeptalk.svc.cluster.local:18123/api/chat/ws;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
            }
            location /api {
                proxy_pass http://deeptalk-xboom.deeptalk.svc.cluster.local:18123/api;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                client_max_body_size 400M;
            }
            location /docs {
                proxy_pass http://deeptalk-xboom.deeptalk.svc.cluster.local:18123/docs;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
            # location /dashboard {
            #     proxy_pass http://deeptalk-clash.deeptalk.svc.cluster.local:80/dashboard;
            #     proxy_set_header Host $host;
            #     proxy_set_header X-Real-IP $remote_addr;
            #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # }
            location ~ ^/clash(/.*)?$ {
                proxy_pass http://10.43.84.91:9090$1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
            location = /openapi.json {
                proxy_pass http://deeptalk-xboom.deeptalk.svc.cluster.local:18123/openapi.json;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
            location / {
                root /usr/local/nginx/html;
                try_files $uri $uri/ /index.html;
            }
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: deeptalk-web
  namespace: deeptalk
spec:
  ports:
    - port: 18123
      name: "web-port-18123"
      protocol: TCP
      targetPort: 18123
      nodePort: 18123
  selector:
    app: deeptalk-web
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deeptalk-web
  namespace: deeptalk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deeptalk-web
  template:
    metadata:
      labels:
        app: deeptalk-web
    spec:
      containers:
        - name: deeptalk-web
          image: registry.jxit.net.cn:5000/deeptalk/deeptalk-web:https_allow_http
          command: ["/usr/local/nginx/sbin/nginx", "-g", "daemon off;"]
          ports:
            - containerPort: 18123
          volumeMounts:
            - name: web-src
              mountPath: /usr/local/nginx/html
            - name: web-install
              mountPath: /usr/local/nginx/install
            - name: buildin-src
              mountPath: /usr/local/nginx/buildin
            - name: nginx-config
              mountPath: /usr/local/nginx/conf/nginx.conf
              subPath: nginx.conf
            - name: nginx-selfsigned-key
              mountPath: /usr/local/nginx/conf/certs/nginx-selfsigned.key
              subPath: nginx-selfsigned.key
            - name: nginx-selfsigned-crt
              mountPath: /usr/local/nginx/conf/certs/nginx-selfsigned.crt
              subPath: nginx-selfsigned.crt
      volumes:
        - name: web-src
          persistentVolumeClaim:
            claimName: deeptalk-web-src
        - name: web-install
          persistentVolumeClaim:
            claimName: deeptalk-web-install
        - name: buildin-src
          persistentVolumeClaim:
            claimName: deeptalk-buildin-src
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: nginx-selfsigned-key
          configMap:
            name: nginx-selfsigned-key
            items:
              - key: nginx-selfsigned.key
                path: nginx-selfsigned.key
        - name: nginx-selfsigned-crt
          configMap:
            name: nginx-selfsigned-crt
            items:
              - key: nginx-selfsigned.crt
                path: nginx-selfsigned.crt
