apiVersion: v1
kind: Service
metadata:
  name: deeptalk-xboom-aiteacher
  namespace: deeptalk
spec:
  ports:
    - port: 18126
      name: "xboom-aiteacher-port-18126"
      protocol: TCP
      targetPort: 8000
  selector:
    app: deeptalk-xboom-aiteacher
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deeptalk-xboom-aiteacher
  namespace: deeptalk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deeptalk-xboom-aiteacher
  template:
    metadata:
      labels:
        app: deeptalk-xboom-aiteacher
    spec:
      containers:
        - name: deeptalk-xboom-aiteacher
          image: registry.jxit.net.cn:5000/deeptalk/xboom:git-1455
          command: ["sleep", "88888888888888"]
          # command: ["python3", "run.py", "--host", "0.0.0.0", "--port", "8000", "--reload", "False", "--workers", "1"]
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: xboom-aiteacher-src
              mountPath: /app
            - name: xboom-data
              mountPath: /data
      volumes:
        - name: xboom-aiteacher-src
          persistentVolumeClaim:
            claimName: deeptalk-xboom-aiteacher-src
        - name: xboom-data
          persistentVolumeClaim:
            claimName: deeptalk-xboom-data
