apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deeptalk-mongo-backup-pvc
  namespace: deeptalk
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
