apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deeptalk-xboom-src
  namespace: deeptalk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deeptalk-xboom-data
  namespace: deeptalk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
